workflows:
  ios-build:
    name: iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios
      - name: Bundle and Force Link
        script: |
          # 1. Create the bundle for Expo Router
          npx expo export:embed \
            --platform ios \
            --dev false \
            --entry-file node_modules/expo-router/entry.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios
      - name: Build and Inject
        script: |
          # 1. Build the Archive
          xcodebuild archive \
            -workspace ios/*.xcworkspace \
            -scheme UniSchedule \
            -configuration Debug \
            -archivePath build/ios/export.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_METHOD=manual
          
          # 2. PHYSICAL INJECTION: 
          # This forces the bundle into the .app folder inside the archive
          APP_PATH=$(find build/ios/export.xcarchive -name "*.app")
          cp ios/main.jsbundle "$APP_PATH/main.jsbundle"
          echo "Bundle injected into: $APP_PATH"
    artifacts:
      - build/ios/export.xcarchive