workflows:
  ios-build:
    name: iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios
      - name: Bundle and Inject JS
        script: |
          # 1. Create the bundle manually
          npx expo export:embed \
            --platform ios \
            --dev false \
            --entry-file node_modules/expo-router/entry.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios
          
          # 2. Inject it into the native project folder
          # Replace 'UniSchedule' with your actual project folder name if different
          mkdir -p ios/UniSchedule
          cp ios/main.jsbundle ios/UniSchedule/main.jsbundle
      - name: Build iOS App
        script: |
          xcodebuild archive \
            -workspace ios/*.xcworkspace \
            -scheme UniSchedule \
            -configuration Debug \
            -archivePath build/ios/export.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_METHOD=manual
    artifacts:
      - build/ios/export.xcarchive