workflows:
  ios-build:
    name: iOS Build (Unsigned Release)
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios
      - name: Bundle and Force Inject
        script: |
          # 1. Generate the JavaScript bundle for Release
          npx expo export:embed \
            --platform ios \
            --dev false \
            --entry-file node_modules/expo-router/entry.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios
          
          # 2. Build the app shell in RELEASE mode (This removes the 'Connect to Metro' screen)
          xcodebuild archive \
            -workspace ios/*.xcworkspace \
            -scheme UniSchedule \
            -configuration Release \
            -archivePath build/ios/export.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_METHOD=manual
          
          # 3. Inject the bundle into the Release package
          APP_DIR=$(find build/ios/export.xcarchive -name "*.app")
          cp ios/main.jsbundle "$APP_DIR/main.jsbundle"
          echo "✅ SUCCESS: Release bundle injected into: $APP_DIR"
    artifacts:
      - build/ios/export.xcarchive